### ISSUE TITLE
Update Okta pipeline to reflect field names

### ISSUE THREAD

**Issue by kelnage** [grafana/pySigma-backend-loki#100]
When [creating new Sigma rules for Okta](https://github.com/SigmaHQ/sigma/pull/4428), it turned out that the naming of the fields is not as consistent as it is originally seemed, and that [certain field names should use full stops](https://github.com/SigmaHQ/sigma/pull/4428#issuecomment-1710184323), whereas the majority use underscores. The [existing Okta pipeline](https://github.com/grafana/pySigma-backend-loki/blob/61d88c02d022936a65aebccb15b24bbb04b4adf2/sigma/pipelines/loki/loki.py#L173) assumes all field names use underscores, so should be updated to reflect this inconsistency.

An up-to-date YAML pipeline used for correctly converting the Sigma Okta rules is as follows:

```yaml
name: Okta JSON pipeline
priority: 20
transformations:
  - id: loki_okta_event_json_formatter
    type: set_custom_attribute
    attribute: loki_parser
    value: json
    rule_conditions:
    - type: logsource
      product: okta
      service: okta
  - id: loki_okta_field_name_mapping
    type: field_name_mapping
    mapping:
      eventtype: eventType
      legacyeventtype: legacyEventType
      actor_alternateid: actor_alternateId
      actor_displayname: actor_displayName
      client_useragent_rawuseragent: client_userAgent_rawUserAgent
      client_useragent_os: client_userAgent_os
      client_useragent_browser: client_userAgent_browser
      client_geographicalcontext_geolocation_lat: client_geographicalContext_geolocation_lat
      client_geographicalcontext_geolocation_lon: client_geographicalContext_geolocation_lon
      client_geographicalcontext_city: client_geographicalContext_city
      client_geographicalcontext_state: client_geographicalContext_state
      client_geographicalcontext_country: client_geographicalContext_country
      client_geographicalcontext_postalcode: client_geographicalContext_postalCode
      client_ipaddress: client_ipAddress
      debugcontext_debugdata_requesturi: debugContext_debugData_requestUri
      debugcontext_debugdata_originalprincipal_id: debugContext_debugData_originalPrincipal_id
      debugcontext_debugdata_originalprincipal_type: debugContext_debugData_originalPrincipal_type
      debugcontext_debugdata_originalprincipal_alternateid: debugContext_debugData_originalPrincipal_alternateId
      debugcontext_debugdata_originalprincipal_displayname: debugContext_debugData_originalPrincipal_displayName
      debugcontext_debugdata_behaviors: debugContext_debugData_behaviors
      debugcontext_debugdata_logonlysecuritydata: debugContext_debugData_logOnlySecurityData
      authenticationcontext_authenticationprovider: authenticationContext_authenticationProvider
      authenticationcontext_authenticationstep: authenticationContext_authenticationStep
      authenticationcontext_credentialprovider: authenticationContext_credentialProvider
      authenticationcontext_credentialtype: authenticationContext_credentialType
      authenticationcontext_issuer_id: authenticationContext_issuer_id
      authenticationcontext_issuer_type: authenticationContext_issuer_type
      authenticationcontext_externalsessionid: authenticationContext_externalSessionId
      authenticationcontext_interface: authenticationContext_interface
      securitycontext.asnumber: securityContext_asNumber
      securitycontext.asorg: securityContext_asOrg
      securitycontext.isp: securityContext_isp
      securitycontext.domain: securityContext_domain
      securitycontext.isproxy: securityContext_isProxy
      target.alternateid: target_alternateId
      target.displayname: target_displayName
      target.detailentry: target_detailEntry
    rule_conditions:
    - type: logsource
      product: okta
      service: okta
  - id: loki_okta_field_event_prefix
    type: field_name_prefix
    prefix: event_
    rule_conditions:
    - type: logsource
      product: okta
      service: okta
```
