### ISSUE TITLE
`set_custom_log_source` attempting to access field of ConditionValueExpression

### ISSUE THREAD

**Issue by kelnage** [grafana/pySigma-backend-loki#186]
When converting [the following rule](https://github.com/SigmaHQ/sigma/blob/24b9ed72c173c81b483699bad2730748fdc312e1/rules/cloud/gcp/audit/gcp_breakglass_container_workload_deployed.yml):
```yaml
title: GCP Break-glass Container Workload Deployed
id: 76737c19-66ee-4c07-b65a-a03301d1573d
status: experimental
description: |
    Detects the deployment of workloads that are deployed by using the break-glass flag to override Binary Authorization controls.
references:
    - https://cloud.google.com/binary-authorization
author: Bryan Lim
date: 2024/01/12
tags:
    - attack.defense_evasion
    - attack.t1548
logsource:
    product: gcp
    service: gcp.audit
detection:
    selection:
        data.protoPayload.resource.type: 'k8s_cluster'
        data.protoPayload.logName:
            - 'cloudaudit.googleapis.com/activity'
            - 'cloudaudit.googleapis.com%2Factivity'
        data.protoPayload.methodName: 'io.k8s.core.v1.pods.create'
    keywords:
        - 'image-policy.k8s.io/break-glass'
    condition: selection and keywords
falsepositives:
    - Unknown
level: medium
```
with the following pipeline:
```yaml
name: gcp_audit_logs
priority: 20
transformations:
    - id: method_name_mapping
      type: field_name_mapping
      mapping:
        gcp.audit.method_name: protoPayload_methodName
        data.protoPayload.methodName: protoPayload_methodName
        data.protoPayload.logName: logname
        data.protoPayload.resource.type: resource_type
        data.protoPayload.serviceName: protoPayload_serviceName
    - id: custom_log_source
      type: set_custom_log_source
      selection:
          job: integrations/gcp
          protoPayload_methodName|fieldref: protoPayload_methodName
          protoPayload_serviceName|fieldref: protoPayload_serviceName
          logname|fieldref: logname
          resource_type|fieldref: resource_type
```
a fatal exception is being thrown:
```
Traceback (most recent call last):
...
  File "/home/nick/.cache/pypoetry/virtualenvs/sigma-cli-UK5x4Xiv-py3.9/lib/python3.9/site-packages/sigma/pipelines/loki/loki.py", line 167, in apply
    if item.field == value.field and isinstance(
AttributeError: 'ConditionValueExpression' object has no attribute 'field' (while applying processing pipeline on rule /home/nick/git/sigma/rules/cloud/gcp/audit/gcp_breakglass_container_workload_deployed.yml)
```
